---
name: Build on Main

'on':
  push:
    branches: [main]

jobs:
  call-ci:
    uses: x-delfino/ansible-ci/.github/workflows/collection.yml@main
    with:
      namespace: x_delfino
      collection: common
      run_build: true
