---
name: PR Checks

'on':
  pull_request:
    branches: [main]

jobs:
  call-ci:
    uses: x-delfino/ansible-ci/.github/workflows/collection.yml@main
    with:
      namespace: x_delfino
      collection: common
